### ISSUE TITLE
Consider not using direct child selector

### ISSUE THREAD

**Issue by studnitz** [GeoffSelby/tailwind-md-base#1]
Hey there,

thanks for the plugin! As I tried it I noticed one issue for me:

The markdown generation module I'm using outputs the following markup:

```html
<div class="markdown">
  <!-- the article tag is auto-generated and I can't add a class easily -->
  <article>
    <h1>Something</h1>
  </article>
</div>
```

This leads obviously to the styles not working.

So my question is if you could change that you generate `.markdown h1` instead of `.markdown > h1`. I think allowing to be more flexible here would only have benefits as I as the one who adds the wrapper class am already aware that all its childs will have the `md-base` styling. :)

**Comment by GeoffSelby** [comment]
Wow I didn’t know some markdown generators added a wrapper element like that. I’ll remove the specificity from the generated classes later today.
